nkaba/config/routes.rb
Rails.application.routes.draw do
  resources :doctor_hospitals
  resources :require_tests
  resources :evaluate_doctors
  resources :evaluate_labs
  resources :evaluate_hosptials
  resources :relatives
  resources :transfers
  resources :complaints
  resources :types
  resources :doctors
  resources :labs
  resources :hospitals
  resources :engineers
  resources :limits

end

nkaba/app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :lab
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

nkaba/app/models/doctor_hospital.rb
class DoctorHospital < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :doctor
end

nkaba/app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :limit
end

nkaba/app/models/evaluate_doctor.rb
class EvaluateDoctor < ActiveRecord::Base
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_hosptial.rb
class EvaluateHosptial < ActiveRecord::Base
  belongs_to :hospital
   has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_lab.rb
class EvaluateLab < ActiveRecord::Base
  belongs_to :lab
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

nkaba/app/models/lab.rb
class Lab < ActiveRecord::Base
end

nkaba/app/models/limit.rb
class Limit < ActiveRecord::Base
  has_many :engineers
end

nkaba/app/models/relative.rb
class Relative < ActiveRecord::Base
  belongs_to :limit
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/require_test.rb
class RequireTest < ActiveRecord::Base
  belongs_to :transfer
end

nkaba/app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :hospital
  belongs_to :lab
  belongs_to :type
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/type.rb
class Type < ActiveRecord::Base
end

nkaba/app/controllers/doctors_controller.rb
class DoctorsController < InheritedResources::Base

  private

    def doctor_params
      params.require(:doctor).permit(:name, :degree, :specialization, :address, :phone, :governorate, :area, :price, :time_from, :time_to, :mobile, :rate)
    end
end

nkaba/app/helpers/doctors_helper.rb
module DoctorsHelper
end

nkaba/app/helpers/engineers_helper.rb
module EngineersHelper
end

nkaba/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

nkaba/app/helpers/labs_helper.rb
module LabsHelper
end

nkaba/app/helpers/limits_helper.rb
module LimitsHelper
end

nkaba/app/helpers/relatives_helper.rb
module RelativesHelper
end

nkaba/app/helpers/transfers_helper.rb
module TransfersHelper
end

nkaba/app/helpers/types_helper.rb
module TypesHelper
end

nkaba/app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.text_field :degree %>
  </div>
  <div class="field">
    <%= f.label :specialization %><br>
    <%= f.text_field :specialization %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :governorate %><br>
    <%= f.text_field :governorate %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :time_from %><br>
    <%= f.text_field :time_from %>
  </div>
  <div class="field">
    <%= f.label :time_to %><br>
    <%= f.text_field :time_to %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nkaba/app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

nkaba/app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Degree</th>
      <th>Specialization</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Governorate</th>
      <th>Area</th>
      <th>Price</th>
      <th>Time from</th>
      <th>Time to</th>
      <th>Mobile</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.degree %></td>
        <td><%= doctor.specialization %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.governorate %></td>
        <td><%= doctor.area %></td>
        <td><%= doctor.price %></td>
        <td><%= doctor.time_from %></td>
        <td><%= doctor.time_to %></td>
        <td><%= doctor.mobile %></td>
        <td><%= doctor.rate %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

nkaba/app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

nkaba/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Degree:</strong>
  <%= @doctor.degree %>
</p>

<p>
  <strong>Specialization:</strong>
  <%= @doctor.specialization %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @doctor.phone %>
</p>

<p>
  <strong>Governorate:</strong>
  <%= @doctor.governorate %>
</p>

<p>
  <strong>Area:</strong>
  <%= @doctor.area %>
</p>

<p>
  <strong>Price:</strong>
  <%= @doctor.price %>
</p>

<p>
  <strong>Time from:</strong>
  <%= @doctor.time_from %>
</p>

<p>
  <strong>Time to:</strong>
  <%= @doctor.time_to %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @doctor.mobile %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @doctor.rate %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>