nkaba/config/routes.rb
Rails.application.routes.draw do
  resources :doctor_hospitals
  resources :require_tests
  resources :evaluate_doctors
  resources :evaluate_labs
  resources :evaluate_hosptials
  resources :relatives
  resources :transfers
  resources :complaints
  resources :types
  resources :doctors
  resources :labs
  resources :hospitals
  resources :engineers
  resources :limits

end

nkaba/app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :lab
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

nkaba/app/models/doctor_hospital.rb
class DoctorHospital < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :doctor
end

nkaba/app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :limit
end

nkaba/app/models/evaluate_doctor.rb
class EvaluateDoctor < ActiveRecord::Base
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_hosptial.rb
class EvaluateHosptial < ActiveRecord::Base
  belongs_to :hospital
   has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_lab.rb
class EvaluateLab < ActiveRecord::Base
  belongs_to :lab
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

nkaba/app/models/lab.rb
class Lab < ActiveRecord::Base
end

nkaba/app/models/limit.rb
class Limit < ActiveRecord::Base
  has_many :engineers
end

nkaba/app/models/relative.rb
class Relative < ActiveRecord::Base
  belongs_to :limit
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/require_test.rb
class RequireTest < ActiveRecord::Base
  belongs_to :transfer
end

nkaba/app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :hospital
  belongs_to :lab
  belongs_to :type
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/type.rb
class Type < ActiveRecord::Base
end

nkaba/app/controllers/limits_controller.rb
class LimitsController < InheritedResources::Base

  private

    def limit_params
      params.require(:limit).permit(:remainder_of_total, :credit_of_surgeries, :credit_medical_tests_rumors)
    end
end

nkaba/app/helpers/doctors_helper.rb
module DoctorsHelper
end

nkaba/app/helpers/engineers_helper.rb
module EngineersHelper
end

nkaba/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

nkaba/app/helpers/labs_helper.rb
module LabsHelper
end

nkaba/app/helpers/limits_helper.rb
module LimitsHelper
end

nkaba/app/helpers/relatives_helper.rb
module RelativesHelper
end

nkaba/app/helpers/transfers_helper.rb
module TransfersHelper
end

nkaba/app/helpers/types_helper.rb
module TypesHelper
end

nkaba/app/views/limits/_form.html.erb
<%= form_for(@limit) do |f| %>
  <% if @limit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@limit.errors.count, "error") %> prohibited this limit from being saved:</h2>

      <ul>
      <% @limit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :remainder_of_total %><br>
    <%= f.text_field :remainder_of_total %>
  </div>
  <div class="field">
    <%= f.label :credit_of_surgeries %><br>
    <%= f.text_field :credit_of_surgeries %>
  </div>
  <div class="field">
    <%= f.label :credit_medical_tests_rumors %><br>
    <%= f.text_field :credit_medical_tests_rumors %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nkaba/app/views/limits/edit.html.erb
<h1>Editing Limit</h1>

<%= render 'form' %>

<%= link_to 'Show', @limit %> |
<%= link_to 'Back', limits_path %>

nkaba/app/views/limits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Limits</h1>

<table>
  <thead>
    <tr>
      <th>Remainder of total</th>
      <th>Credit of surgeries</th>
      <th>Credit medical tests rumors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @limits.each do |limit| %>
      <tr>
        <td><%= limit.remainder_of_total %></td>
        <td><%= limit.credit_of_surgeries %></td>
        <td><%= limit.credit_medical_tests_rumors %></td>
        <td><%= link_to 'Show', limit %></td>
        <td><%= link_to 'Edit', edit_limit_path(limit) %></td>
        <td><%= link_to 'Destroy', limit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Limit', new_limit_path %>

nkaba/app/views/limits/new.html.erb
<h1>New Limit</h1>

<%= render 'form' %>

<%= link_to 'Back', limits_path %>

nkaba/app/views/limits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Remainder of total:</strong>
  <%= @limit.remainder_of_total %>
</p>

<p>
  <strong>Credit of surgeries:</strong>
  <%= @limit.credit_of_surgeries %>
</p>

<p>
  <strong>Credit medical tests rumors:</strong>
  <%= @limit.credit_medical_tests_rumors %>
</p>

<%= link_to 'Edit', edit_limit_path(@limit) %> |
<%= link_to 'Back', limits_path %>