nkaba/config/routes.rb
Rails.application.routes.draw do
  resources :doctor_hospitals
  resources :require_tests
  resources :evaluate_doctors
  resources :evaluate_labs
  resources :evaluate_hosptials
  resources :relatives
  resources :transfers
  resources :complaints
  resources :types
  resources :doctors
  resources :labs
  resources :hospitals
  resources :engineers
  resources :limits

end

nkaba/app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :lab
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

nkaba/app/models/doctor_hospital.rb
class DoctorHospital < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :doctor
end

nkaba/app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :limit
end

nkaba/app/models/evaluate_doctor.rb
class EvaluateDoctor < ActiveRecord::Base
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_lab.rb
class EvaluateLab < ActiveRecord::Base
  belongs_to :lab
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

nkaba/app/models/lab.rb
class Lab < ActiveRecord::Base
end

nkaba/app/models/limit.rb
class Limit < ActiveRecord::Base
  has_many :engineers
end

nkaba/app/models/relative.rb
class Relative < ActiveRecord::Base
  belongs_to :limit
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/require_test.rb
class RequireTest < ActiveRecord::Base
  belongs_to :transfer
end

nkaba/app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :hospital
  belongs_to :lab
  belongs_to :type
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/type.rb
class Type < ActiveRecord::Base
end

nkaba/app/controllers/require_tests_controller.rb
class RequireTestsController < InheritedResources::Base

  private

    def require_test_params
      params.require(:require_test).permit(:transfer_id, :test, :test_id)
    end
end

nkaba/app/helpers/doctors_helper.rb
module DoctorsHelper
end

nkaba/app/helpers/engineers_helper.rb
module EngineersHelper
end

nkaba/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

nkaba/app/helpers/labs_helper.rb
module LabsHelper
end

nkaba/app/helpers/limits_helper.rb
module LimitsHelper
end

nkaba/app/helpers/relatives_helper.rb
module RelativesHelper
end

nkaba/app/helpers/require_tests_helper.rb
module RequireTestsHelper
end

nkaba/app/helpers/transfers_helper.rb
module TransfersHelper
end

nkaba/app/helpers/types_helper.rb
module TypesHelper
end

nkaba/app/views/require_tests/_form.html.erb
<%= form_for(@require_test) do |f| %>
  <% if @require_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@require_test.errors.count, "error") %> prohibited this require_test from being saved:</h2>

      <ul>
      <% @require_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :transfer_id %><br>
    <%= f.text_field :transfer_id %>
  </div>
  <div class="field">
    <%= f.label :test %><br>
    <%= f.text_field :test %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.number_field :test_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nkaba/app/views/require_tests/edit.html.erb
<h1>Editing Require Test</h1>

<%= render 'form' %>

<%= link_to 'Show', @require_test %> |
<%= link_to 'Back', require_tests_path %>

nkaba/app/views/require_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Require Tests</h1>

<table>
  <thead>
    <tr>
      <th>Transfer</th>
      <th>Test</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @require_tests.each do |require_test| %>
      <tr>
        <td><%= require_test.transfer %></td>
        <td><%= require_test.test %></td>
        <td><%= require_test.test_id %></td>
        <td><%= link_to 'Show', require_test %></td>
        <td><%= link_to 'Edit', edit_require_test_path(require_test) %></td>
        <td><%= link_to 'Destroy', require_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Require test', new_require_test_path %>

nkaba/app/views/require_tests/new.html.erb
<h1>New Require Test</h1>

<%= render 'form' %>

<%= link_to 'Back', require_tests_path %>

nkaba/app/views/require_tests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transfer:</strong>
  <%= @require_test.transfer %>
</p>

<p>
  <strong>Test:</strong>
  <%= @require_test.test %>
</p>

<p>
  <strong>Test:</strong>
  <%= @require_test.test_id %>
</p>

<%= link_to 'Edit', edit_require_test_path(@require_test) %> |
<%= link_to 'Back', require_tests_path %>