nkaba/config/routes.rb
Rails.application.routes.draw do
  resources :doctor_hospitals
  resources :require_tests
  resources :evaluate_doctors
  resources :evaluate_labs
  resources :evaluate_hosptials
  resources :relatives
  resources :transfers
  resources :complaints
  resources :types
  resources :doctors
  resources :labs
  resources :hospitals
  resources :engineers
  resources :limits

end

nkaba/app/models/complaint.rb
class Complaint < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :lab
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

nkaba/app/models/doctor_hospital.rb
class DoctorHospital < ActiveRecord::Base
  belongs_to :hospital
  belongs_to :doctor
end

nkaba/app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :limit
end

nkaba/app/models/evaluate_doctor.rb
class EvaluateDoctor < ActiveRecord::Base
  belongs_to :doctor
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/evaluate_lab.rb
class EvaluateLab < ActiveRecord::Base
  belongs_to :lab
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/hospital.rb
class Hospital < ActiveRecord::Base
end

nkaba/app/models/lab.rb
class Lab < ActiveRecord::Base
end

nkaba/app/models/limit.rb
class Limit < ActiveRecord::Base
  has_many :engineers
end

nkaba/app/models/relative.rb
class Relative < ActiveRecord::Base
  belongs_to :limit
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/require_test.rb
class RequireTest < ActiveRecord::Base
  belongs_to :transfer
end

nkaba/app/models/transfer.rb
class Transfer < ActiveRecord::Base
  belongs_to :doctor
  belongs_to :hospital
  belongs_to :lab
  belongs_to :type
  has_one :engineer, foreign_key: 'membersh_number'
end

nkaba/app/models/type.rb
class Type < ActiveRecord::Base
end

nkaba/app/controllers/evaluate_doctors_controller.rb
class EvaluateDoctorsController < InheritedResources::Base

  private

    def evaluate_doctor_params
      params.require(:evaluate_doctor).permit(:doctor_id, :membersh_number, :rate)
    end
end

nkaba/app/helpers/doctors_helper.rb
module DoctorsHelper
end

nkaba/app/helpers/engineers_helper.rb
module EngineersHelper
end

nkaba/app/helpers/evaluate_doctors_helper.rb
module EvaluateDoctorsHelper
end

nkaba/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

nkaba/app/helpers/labs_helper.rb
module LabsHelper
end

nkaba/app/helpers/limits_helper.rb
module LimitsHelper
end

nkaba/app/helpers/relatives_helper.rb
module RelativesHelper
end

nkaba/app/helpers/transfers_helper.rb
module TransfersHelper
end

nkaba/app/helpers/types_helper.rb
module TypesHelper
end

nkaba/app/views/evaluate_doctors/_form.html.erb
<%= form_for(@evaluate_doctor) do |f| %>
  <% if @evaluate_doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluate_doctor.errors.count, "error") %> prohibited this evaluate_doctor from being saved:</h2>

      <ul>
      <% @evaluate_doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.text_field :doctor_id %>
  </div>
  <div class="field">
    <%= f.label :membersh_number %><br>
    <%= f.text_field :membersh_number %>
  </div>
  <div class="field">
    <%= f.label :rate %><br>
    <%= f.text_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nkaba/app/views/evaluate_doctors/edit.html.erb
<h1>Editing Evaluate Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluate_doctor %> |
<%= link_to 'Back', evaluate_doctors_path %>

nkaba/app/views/evaluate_doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluate Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Membersh number</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluate_doctors.each do |evaluate_doctor| %>
      <tr>
        <td><%= evaluate_doctor.doctor %></td>
        <td><%= evaluate_doctor.membersh_number %></td>
        <td><%= evaluate_doctor.rate %></td>
        <td><%= link_to 'Show', evaluate_doctor %></td>
        <td><%= link_to 'Edit', edit_evaluate_doctor_path(evaluate_doctor) %></td>
        <td><%= link_to 'Destroy', evaluate_doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evaluate doctor', new_evaluate_doctor_path %>

nkaba/app/views/evaluate_doctors/new.html.erb
<h1>New Evaluate Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluate_doctors_path %>

nkaba/app/views/evaluate_doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @evaluate_doctor.doctor %>
</p>

<p>
  <strong>Membersh number:</strong>
  <%= @evaluate_doctor.membersh_number %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @evaluate_doctor.rate %>
</p>

<%= link_to 'Edit', edit_evaluate_doctor_path(@evaluate_doctor) %> |
<%= link_to 'Back', evaluate_doctors_path %>